import { Inter } from "next/font/google";
import "./globals.css";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/app/LogoutBtn";
import LoginBtn from "@/app/LoginBtn";
import Link from "next/link";
import ResisterBtn from "@/app/ResisterBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

    let session = await getServerSession(authOptions)
    console.log(session)

    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <div className={"navbar"}>
                        <div className={"left-nav"}>
                            <Link href={"/"}>Too_many_Do!</Link>
                            <Link href={"/list"}>리스트📜</Link>
                        </div>
                        <div className={"right-nav"}>
                            {
                                session ? <LogoutBtn></LogoutBtn> : <LoginBtn></LoginBtn>
                            }
                            {
                                session ? <p>{session.user.name}</p> : <ResisterBtn></ResisterBtn>
                            }
                        </div>
                    </div>
                </div>
            {children}
        </body>
    </html>
  );
}
